dubbo:
  application:
    name: boot-user-service-provider
  registry:
    protocol: zookeeper
    address: 47.106.182.44:2181
  protocol:
    name: dubbo
    port: 20881
  monitor:
    protocol: registry
